// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

#if UNITY_ANDROID

using System;
using System.IO;
using System.Runtime.Serialization.Formatters.Binary;
using GooglePlayGames;
using GooglePlayGames.BasicApi;
using GooglePlayGames.BasicApi.SavedGame;
using UnityEngine;
using UnityEngine.SocialPlatforms;
using UnityEngine.UI;
///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

public class  GooglePlayServiceCtrl : MonoBehaviour, IMobilePlatform
{

    const string leaderboardId = GooglePlayServiceInfo.leaderboard_hexa_puzzle_2048;
	public void Init()
    {

        Debug.Log("gbros GooglePlayServiceCtrl Init start");
        
		PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
            //.EnableSavedGames()
            .AddOauthScope("profile")
            // .AddOauthScope("https://www.googleapis.com/auth/games")
            // .AddOauthScope("https://www.googleapis.com/auth/plus.login")
            .Build();

        // PlayGamesClientConfiguration config = new PlayGamesClientConfiguration.Builder()
        // // enables saving game progress.
        // .EnableSavedGames()
        // .RequestEmail()
        // // requests a server auth code be generated so it can be passed to an
        // //  associated back end server application and exchanged for an OAuth token.
        // .RequestServerAuthCode(false)
        // // requests an ID token be generated.  This OAuth token can be used to
        // //  identify the player to other services such as Firebase.
        // .RequestIdToken()
        // .Build();
 
        PlayGamesPlatform.InitializeInstance(config);

        // recommended for debugging:
        if(BuildManager.Instance.GetBuildPhase() == BUILD_PHASE.DEV)
            PlayGamesPlatform.DebugLogEnabled = true;
        
        // Activate the Google Play Games platform
        PlayGamesPlatform.Activate ();

        Debug.Log("gbros GooglePlayServiceCtrl Init end");
        
    }

    public void GetLeaderboardScore(ActionObject<IScore> callback = null){
        
        PlayGamesPlatform.Instance.LoadScores(leaderboardId
        , LeaderboardStart.PlayerCentered
        , 1
        , LeaderboardCollection.Public
        , LeaderboardTimeSpan.AllTime
        , (data)=>{
            Debug.Log("gbros " + data.PlayerScore.userID + " / rank: " + data.PlayerScore.rank + " / value :" +data.PlayerScore.value +" / formattedValue : " + data.PlayerScore.formattedValue);
        });
    }

	public void LogIn (ActionBool onLogIn=null)
    {
        Debug.Log("gbros LogIn IsAuthenticated : " + PlayGamesPlatform.Instance.IsAuthenticated());
        
        PlayGamesPlatform.Instance.Authenticate ((bool success, string msg) =>
        {
            if (success) {
                Debug.Log ("gbros Login Sucess : " + PlayGamesPlatform.Instance.GetUserId() + "| msg : " + msg);
                if(onLogIn!=null)
                    onLogIn.Invoke(true);                
            } else {
                Debug.Log ("gbros Login failed" + "| msg : " + msg);
                if(onLogIn!=null)
                    onLogIn.Invoke(false);
            }
        });
    }

	public void ShowLeaderBoard ()
    {
        PlayGamesPlatform.Instance.ShowLeaderboardUI(leaderboardId); // Show current (Active) leaderboard
    }

	public void AddScoreToLeaderBorad (long score)
    {
        Debug.Log ("gbros AddScoreToLeaderBorad : " + score);
        if (IsLoggedIn()) {
            PlayGamesPlatform.Instance.ReportScore (score, leaderboardId, (bool success) =>
            {
                if (success) {
                    Debug.Log ("Update Score Success");                    
                } else {
                    Debug.Log ("Update Score Fail");
                }
            });
            
            // AnalyticsManager.Instance.EventLog(FirebaseAnalytics.EventPostScore, new AnalyticsEventParam()
            // .AddParam("leaderboard_id", GooglePlayServiceInfo.leaderboard_challenge_find_the_difference)
            // .AddParam(FirebaseAnalytics.ParameterScore, score));
        }
    }

	public void LogOut ()
    {
        PlayGamesPlatform.Instance.SignOut ();
    }

    public bool IsLoggedIn(){
        return PlayGamesPlatform.Instance.IsAuthenticated();
    }

    public string GetUserId(){
        return IsLoggedIn() ? PlayGamesPlatform.Instance.GetUserId() : string.Empty;
    }


    // const string cloudfileName = "userdata";
    // public void SaveToCloud()
    // {
    //     if (!IsLoggedIn()) //로그인되지 않았으면
    //     {
    //         return;
    //     }
 
    //     OpenSavedGame(cloudfileName, true);
    // }
 
    // private void OpenSavedGame(string filename, bool bSave)
    // {
    //     ISavedGameClient savedGameClient = PlayGamesPlatform.Instance.SavedGame;
 
    //     if (bSave)
    //         savedGameClient.OpenWithAutomaticConflictResolution(filename, DataSource.ReadCacheOrNetwork, ConflictResolutionStrategy.UseLongestPlaytime, OnSavedGameOpenedToSave); //저장루틴진행
    //     else
    //         savedGameClient.OpenWithAutomaticConflictResolution(filename, DataSource.ReadCacheOrNetwork, ConflictResolutionStrategy.UseLongestPlaytime, OnSavedGameOpenedToRead); //로딩루틴 진행
    // }
 
    // private void OnSavedGameOpenedToSave(SavedGameRequestStatus status, ISavedGameMetadata game)
    // {
    //     if (status == SavedGameRequestStatus.Success)
    //     {
    //         SaveGame(game, ObjectUtil.ToByteArray(DataManager.Instance.UserData), DateTime.Now.TimeOfDay);
    //     }
    //     else
    //     {
    //         Debug.Log ("gbros 파일열기에 실패 ");
    //     }
    // }
 
    // private void SaveGame(ISavedGameMetadata game, byte[] savedData, TimeSpan totalPlaytime)
    // {
    //     ISavedGameClient savedGameClient = PlayGamesPlatform.Instance.SavedGame;
 
    //     SavedGameMetadataUpdate.Builder builder = new SavedGameMetadataUpdate.Builder();
    //     builder = builder
    //         .WithUpdatedPlayedTime(totalPlaytime)
    //         .WithUpdatedDescription("Saved game at " + DateTime.Now);
 
    //     SavedGameMetadataUpdate updatedMetadata = builder.Build();
    //     savedGameClient.CommitUpdate(game, updatedMetadata, savedData, OnSavedGameWritten);
    // }
 
    // private void OnSavedGameWritten(SavedGameRequestStatus status, ISavedGameMetadata game)
    // {
    //     if (status == SavedGameRequestStatus.Success)
    //     {
    //         Debug.Log ("gbros 데이터 저장이 완료");
    //         DataManager.Instance.UserData.IsSync = true;
    //     }
    //     else
    //     {
    //         Debug.Log ("gbros 데이터 저장이 실패");
    //         DataManager.Instance.UserData.IsSync = false;
    //     }
    // }
 
    // //----------------------------------------------------------------------------------------------------------------
    // //클라우드로 부터 파일읽기
    // private ActionObject<UserData> _onLoadData;
    // public void LoadFromCloud(ActionObject<UserData> onLoadData)
    // {
    //     if (!IsLoggedIn())
    //     {
    //         return;
    //     }
    //     _onLoadData = onLoadData;
    //     OpenSavedGame(cloudfileName, false);
    // }
 
    // void OnSavedGameOpenedToRead(SavedGameRequestStatus status, ISavedGameMetadata game)
    // {
    //     if (status == SavedGameRequestStatus.Success)
    //     {
    //         LoadGameData(game);
    //     }
    //     else
    //     {
    //         Debug.Log ("gbros 파일열기에 실패");
    //         if(_onLoadData!=null) _onLoadData(null);
    //     }
    // }
 
    // void LoadGameData(ISavedGameMetadata game)
    // {
    //     ISavedGameClient savedGameClient = PlayGamesPlatform.Instance.SavedGame;
    //     savedGameClient.ReadBinaryData(game, OnSavedGameDataRead);
    // }
 
    // void OnSavedGameDataRead(SavedGameRequestStatus status, byte[] data)
    // {
    //     if (status == SavedGameRequestStatus.Success)
    //     {
    //         UserData userData = ObjectUtil.FromByteArray<UserData>(data);
    //         Debug.Log ("gbros IsOnSound : " + userData.IsOnSound + " / Score : " + userData.Score);
    //         if(_onLoadData!=null) _onLoadData(userData);
    //     }
    //     else
    //     {
    //         Debug.Log ("gbros 읽기에 실패");
    //         if(_onLoadData!=null) _onLoadData(null);
    //     }
    // }

}
#endif
