// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBuffersModel
{

using global::System;
using global::FlatBuffers;

public struct CellModel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static CellModel GetRootAsCellModel(ByteBuffer _bb) { return GetRootAsCellModel(_bb, new CellModel()); }
  public static CellModel GetRootAsCellModel(ByteBuffer _bb, CellModel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public CellModel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short X { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)0; } }
  public short Y { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)0; } }
  public int Value { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<CellModel> CreateCellModel(FlatBufferBuilder builder,
      short x = 0,
      short y = 0,
      int value = 0) {
    builder.StartObject(3);
    CellModel.AddValue(builder, value);
    CellModel.AddY(builder, y);
    CellModel.AddX(builder, x);
    return CellModel.EndCellModel(builder);
  }

  public static void StartCellModel(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddX(FlatBufferBuilder builder, short x) { builder.AddShort(0, x, 0); }
  public static void AddY(FlatBufferBuilder builder, short y) { builder.AddShort(1, y, 0); }
  public static void AddValue(FlatBufferBuilder builder, int value) { builder.AddInt(2, value, 0); }
  public static Offset<CellModel> EndCellModel(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<CellModel>(o);
  }
};


}
