// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBuffersModel
{

using global::System;
using global::FlatBuffers;

public struct ItemUserModel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ItemUserModel GetRootAsItemUserModel(ByteBuffer _bb) { return GetRootAsItemUserModel(_bb, new ItemUserModel()); }
  public static ItemUserModel GetRootAsItemUserModel(ByteBuffer _bb, ItemUserModel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ItemUserModel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ItemType ItemType { get { int o = __p.__offset(4); return o != 0 ? (ItemType)__p.bb.GetSbyte(o + __p.bb_pos) : ItemType.TRASH; } }
  public int Count { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<ItemUserModel> CreateItemUserModel(FlatBufferBuilder builder,
      ItemType itemType = ItemType.TRASH,
      int count = 0) {
    builder.StartObject(2);
    ItemUserModel.AddCount(builder, count);
    ItemUserModel.AddItemType(builder, itemType);
    return ItemUserModel.EndItemUserModel(builder);
  }

  public static void StartItemUserModel(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddItemType(FlatBufferBuilder builder, ItemType itemType) { builder.AddSbyte(0, (sbyte)itemType, 0); }
  public static void AddCount(FlatBufferBuilder builder, int count) { builder.AddInt(1, count, 0); }
  public static Offset<ItemUserModel> EndItemUserModel(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ItemUserModel>(o);
  }
};


}
