// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBuffersModel
{

using global::System;
using global::FlatBuffers;

public struct LastPartsModel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static LastPartsModel GetRootAsLastPartsModel(ByteBuffer _bb) { return GetRootAsLastPartsModel(_bb, new LastPartsModel()); }
  public static LastPartsModel GetRootAsLastPartsModel(ByteBuffer _bb, LastPartsModel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public LastPartsModel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int AngleValue { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int CellPartsArray(int j) { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int CellPartsArrayLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCellPartsArrayBytes() { return __p.__vector_as_span(6); }
#else
  public ArraySegment<byte>? GetCellPartsArrayBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public int[] GetCellPartsArrayArray() { return __p.__vector_as_array<int>(6); }

  public static Offset<LastPartsModel> CreateLastPartsModel(FlatBufferBuilder builder,
      int angleValue = 0,
      VectorOffset cellPartsArrayOffset = default(VectorOffset)) {
    builder.StartObject(2);
    LastPartsModel.AddCellPartsArray(builder, cellPartsArrayOffset);
    LastPartsModel.AddAngleValue(builder, angleValue);
    return LastPartsModel.EndLastPartsModel(builder);
  }

  public static void StartLastPartsModel(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddAngleValue(FlatBufferBuilder builder, int angleValue) { builder.AddInt(0, angleValue, 0); }
  public static void AddCellPartsArray(FlatBufferBuilder builder, VectorOffset cellPartsArrayOffset) { builder.AddOffset(1, cellPartsArrayOffset.Value, 0); }
  public static VectorOffset CreateCellPartsArrayVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateCellPartsArrayVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartCellPartsArrayVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<LastPartsModel> EndLastPartsModel(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<LastPartsModel>(o);
  }
};


}
