// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBuffersModel
{

using global::System;
using global::FlatBuffers;

public struct PlayModel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static PlayModel GetRootAsPlayModel(ByteBuffer _bb) { return GetRootAsPlayModel(_bb, new PlayModel()); }
  public static PlayModel GetRootAsPlayModel(ByteBuffer _bb, PlayModel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public PlayModel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Score { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Coin { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int AdContinueWatchCount { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public CellModel? CellArray(int j) { int o = __p.__offset(10); return o != 0 ? (CellModel?)(new CellModel()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int CellArrayLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
  public LastPartsModel? LastPartsData { get { int o = __p.__offset(12); return o != 0 ? (LastPartsModel?)(new LastPartsModel()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public int ItemUseCountArray(int j) { int o = __p.__offset(14); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int ItemUseCountArrayLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetItemUseCountArrayBytes() { return __p.__vector_as_span(14); }
#else
  public ArraySegment<byte>? GetItemUseCountArrayBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public int[] GetItemUseCountArrayArray() { return __p.__vector_as_array<int>(14); }

  public static Offset<PlayModel> CreatePlayModel(FlatBufferBuilder builder,
      int score = 0,
      int coin = 0,
      int adContinueWatchCount = 0,
      VectorOffset cellArrayOffset = default(VectorOffset),
      Offset<LastPartsModel> lastPartsDataOffset = default(Offset<LastPartsModel>),
      VectorOffset itemUseCountArrayOffset = default(VectorOffset)) {
    builder.StartObject(6);
    PlayModel.AddItemUseCountArray(builder, itemUseCountArrayOffset);
    PlayModel.AddLastPartsData(builder, lastPartsDataOffset);
    PlayModel.AddCellArray(builder, cellArrayOffset);
    PlayModel.AddAdContinueWatchCount(builder, adContinueWatchCount);
    PlayModel.AddCoin(builder, coin);
    PlayModel.AddScore(builder, score);
    return PlayModel.EndPlayModel(builder);
  }

  public static void StartPlayModel(FlatBufferBuilder builder) { builder.StartObject(6); }
  public static void AddScore(FlatBufferBuilder builder, int score) { builder.AddInt(0, score, 0); }
  public static void AddCoin(FlatBufferBuilder builder, int coin) { builder.AddInt(1, coin, 0); }
  public static void AddAdContinueWatchCount(FlatBufferBuilder builder, int adContinueWatchCount) { builder.AddInt(2, adContinueWatchCount, 0); }
  public static void AddCellArray(FlatBufferBuilder builder, VectorOffset cellArrayOffset) { builder.AddOffset(3, cellArrayOffset.Value, 0); }
  public static VectorOffset CreateCellArrayVector(FlatBufferBuilder builder, Offset<CellModel>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateCellArrayVectorBlock(FlatBufferBuilder builder, Offset<CellModel>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartCellArrayVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddLastPartsData(FlatBufferBuilder builder, Offset<LastPartsModel> lastPartsDataOffset) { builder.AddOffset(4, lastPartsDataOffset.Value, 0); }
  public static void AddItemUseCountArray(FlatBufferBuilder builder, VectorOffset itemUseCountArrayOffset) { builder.AddOffset(5, itemUseCountArrayOffset.Value, 0); }
  public static VectorOffset CreateItemUseCountArrayVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateItemUseCountArrayVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartItemUseCountArrayVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<PlayModel> EndPlayModel(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<PlayModel>(o);
  }
};


}
