// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBuffersModel
{

using global::System;
using global::FlatBuffers;

public struct UserModel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static UserModel GetRootAsUserModel(ByteBuffer _bb) { return GetRootAsUserModel(_bb, new UserModel()); }
  public static UserModel GetRootAsUserModel(ByteBuffer _bb, UserModel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public UserModel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Score { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Coin { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string DailyRewardDay { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDailyRewardDayBytes() { return __p.__vector_as_span(8); }
#else
  public ArraySegment<byte>? GetDailyRewardDayBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetDailyRewardDayArray() { return __p.__vector_as_array<byte>(8); }
  public string CoinBoxRewardDay { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCoinBoxRewardDayBytes() { return __p.__vector_as_span(10); }
#else
  public ArraySegment<byte>? GetCoinBoxRewardDayBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetCoinBoxRewardDayArray() { return __p.__vector_as_array<byte>(10); }
  public int CointBoxRewardCount { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public long CointBoxRewardTimeStamp { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public PlayModel? PlayData { get { int o = __p.__offset(16); return o != 0 ? (PlayModel?)(new PlayModel()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<UserModel> CreateUserModel(FlatBufferBuilder builder,
      int score = 0,
      int coin = 0,
      StringOffset dailyRewardDayOffset = default(StringOffset),
      StringOffset coinBoxRewardDayOffset = default(StringOffset),
      int cointBoxRewardCount = 0,
      long cointBoxRewardTimeStamp = 0,
      Offset<PlayModel> playDataOffset = default(Offset<PlayModel>)) {
    builder.StartObject(7);
    UserModel.AddCointBoxRewardTimeStamp(builder, cointBoxRewardTimeStamp);
    UserModel.AddPlayData(builder, playDataOffset);
    UserModel.AddCointBoxRewardCount(builder, cointBoxRewardCount);
    UserModel.AddCoinBoxRewardDay(builder, coinBoxRewardDayOffset);
    UserModel.AddDailyRewardDay(builder, dailyRewardDayOffset);
    UserModel.AddCoin(builder, coin);
    UserModel.AddScore(builder, score);
    return UserModel.EndUserModel(builder);
  }

  public static void StartUserModel(FlatBufferBuilder builder) { builder.StartObject(7); }
  public static void AddScore(FlatBufferBuilder builder, int score) { builder.AddInt(0, score, 0); }
  public static void AddCoin(FlatBufferBuilder builder, int coin) { builder.AddInt(1, coin, 0); }
  public static void AddDailyRewardDay(FlatBufferBuilder builder, StringOffset dailyRewardDayOffset) { builder.AddOffset(2, dailyRewardDayOffset.Value, 0); }
  public static void AddCoinBoxRewardDay(FlatBufferBuilder builder, StringOffset coinBoxRewardDayOffset) { builder.AddOffset(3, coinBoxRewardDayOffset.Value, 0); }
  public static void AddCointBoxRewardCount(FlatBufferBuilder builder, int cointBoxRewardCount) { builder.AddInt(4, cointBoxRewardCount, 0); }
  public static void AddCointBoxRewardTimeStamp(FlatBufferBuilder builder, long cointBoxRewardTimeStamp) { builder.AddLong(5, cointBoxRewardTimeStamp, 0); }
  public static void AddPlayData(FlatBufferBuilder builder, Offset<PlayModel> playDataOffset) { builder.AddOffset(6, playDataOffset.Value, 0); }
  public static Offset<UserModel> EndUserModel(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<UserModel>(o);
  }
  public static void FinishUserModelBuffer(FlatBufferBuilder builder, Offset<UserModel> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedUserModelBuffer(FlatBufferBuilder builder, Offset<UserModel> offset) { builder.FinishSizePrefixed(offset.Value); }
};


}
