public enum EventNames
{
    NONE = 0
    ,ON_RAYCAST_SETITEM = 1
   , ON_RAYCAST_UNSETITEM = 2
   , ON_RAYCAST_RECALL_END = 3
   , ON_AUDIO_VOLUME_CTRL = 4
   , ON_NPC_UI_ONOFF


    ,ON_GROUP_MOVE_COMMAND
        , ON_GROUP_MOVE_STOP
        , ON_GROUP_DETECTED_TARGET,
	ON_WEAPON_SWAP,
	ON_BUILDITEM_SELECT,
	ON_BUILDITEM_CANCEL,
    ON_NPC_WAVE_START,
    ON_NPC_DEATH,
    ON_NPC_WAVE_END,
    ON_GAMEOVER,
    ON_TIME_COME_NIGHT,
    ON_TIME_COME_DAYTIME

}